apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-service-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/hasankhairullahdev/helios
    targetRevision: HEAD
    path: infra/helm/notification-service
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: helios-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
