apiVersion: v1
kind: Service
metadata:
  name: {{ include "task-service.fullname" . }}
  labels:
    {{- include "task-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  # ClusterIP = hanya accessible dari dalam cluster.
  # Ingress / API Gateway yang akan expose ke luar — kita tidak butuh itu di project ini.
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "task-service.selectorLabels" . | nindent 4 }}
