{{- if .Values.rollout.enabled }}
# Canary membutuhkan DUA service terpisah:
# - stable-service: traffic ke pod versi lama (stable ReplicaSet)
# - canary-service: traffic ke pod versi baru (canary ReplicaSet)
# Argo Rollouts yang atur selector-nya secara otomatis saat rollout berjalan.
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "task-service.fullname" . }}-stable
  labels:
    {{- include "task-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "task-service.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "task-service.fullname" . }}-canary
  labels:
    {{- include "task-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "task-service.selectorLabels" . | nindent 4 }}

{{- else }}
# DEV: single service biasa
apiVersion: v1
kind: Service
metadata:
  name: {{ include "task-service.fullname" . }}
  labels:
    {{- include "task-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "task-service.selectorLabels" . | nindent 4 }}
{{- end }}
